[project]
name = "service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "numpy>=2.4.1",
    "scipy>=1.17.0",
    "sympy>=1.14.0",
]
